<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Apud.Data\Apud.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Apud.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
